### ISSUE TITLE
SSH host keys are not generated on first start

### ISSUE THREAD

**Issue by spitfire** [sakaki-/gentoo-on-b3#1]
The SSH keys in the image are not generated at startup - therefore everybody who uses your images will trust the same key. This is a big security concern - someone might misuse those keys. Please remove the keys from the image - sshd init script will auto-generate them on startup - it doesn't take long on a b3;)

**Comment by sakaki-** [comment]
Yes, I agree this is a concern - although as I mention in the readme, "if you're intending to use the B3 as an externally visible server, you should change the ssh host keys, change root's password, install a firewall etc". Will do something in this regard for the next release. Best, sakaki

**Comment by sakaki-** [comment]
Released 1.3.1, with the host keys deleted (they are generated afresh on first use).
