### ISSUE TITLE
kirkwood-b3-earlyled.dts requires updating

### ISSUE THREAD

**Issue by gordonb3** [sakaki-/gentoo-on-b3#4]
Current version of the dts has the pcie port moved from mbus to root. If you use the dts as supplied here the resulting kernel with not be able to support the WiFi adapter.

**Comment by sakaki-** [comment]
OK, thanks for the heads up, I'll modify it.

**Comment by gordonb3** [comment]
No worries. I just happened to visit your project(s) because one of your packages pulled in python-updater, only to find that you'd just released an update for that. Seemed appropriate to verify other issues that popped up during the last year and this one had me going for quite some time, trying to figure out why wlan0 was gone.
